services:
  server_node:
    build: ./src/servers
    ports:
      - "3001:3001"
      - "3002:3002"
    networks:
      - haproxy_network

  haproxy:
    image: haproxy:latest
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - server_node
    networks:
      - haproxy_network

networks:
  haproxy_network:
    driver: bridge
